name: Update Gist from Repo Files

on:
  push:
    branches:
      - main

jobs:
  update-gist:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create/Update Gist
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GIST_TOKEN }}
          script: |
            const fs = require('fs');

            // Gist ID (create one manually first, then paste the ID here)
            const gistId = '5836b3b5ba0999950544f5c52bb37076';

            // Files to include in the gist
            const files = {
              'demo01-newuser.MD': { content: fs.readFileSync('demo01-newuser/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo04-vnet.MD': { content: fs.readFileSync('demo04-vnet/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo05-peering.MD': { content: fs.readFileSync('demo05-peering/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo06-nettraffic.MD': { content: fs.readFileSync('demo06-nettraffic/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo07-storageaccount.MD': { content: fs.readFileSync('demo07-storageaccount/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo08-vm-vmss.MD': { content: fs.readFileSync('demo08-vm-vmss/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo09-webapp-continst-contapp.MD': { content: fs.readFileSync('demo09-webapp-continst-contapp/Readme.MD', 'utf8').replace("../imgs/", "") },
              'demo10-dataprotection.MD': { content: fs.readFileSync('demo10-dataprotection/Readme.MD', 'utf8').replace("../imgs/", "") },
              'diag-demo05.png': { content: fs.readFileSync('imgs/diag-demo05.png', 'utf8') },
              'diag-demo06.png': { content: fs.readFileSync('imgs/diag-demo06.png', 'utf8') },
              'diag-demo08.png': { content: fs.readFileSync('imgs/diag-demo08.png', 'utf8') }
            };

            await github.rest.gists.update({
              gist_id: gistId,
              files
            });
